<a href="https://colab.research.google.com/github/jasur-ben-blip/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [4]:
print(pd.__version__)

2.2.2

In [6]:
mydataset = {
    'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
    'counts': [3, 7, 2, 2, 5, 6, 1]
}

df = pd.DataFrame(mydataset)
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       2
4  Ferrari       5
5     Ford       6
6      BMW       1

In [12]:
df.head() # default 5 rows # ketma-ketlikda

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       2
4  Ferrari       5

In [13]:
df.tail() # oxiridan 5 ta ni korsatadi # default 5 rows

      cars  counts
2     Ford       2
3    Tesla       2
4  Ferrari       5
5     Ford       6
6      BMW       1

In [14]:
df.shape

(7, 2)

In [15]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [16]:
df.dtypes

cars      object
counts     int64
dtype: object

In [19]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       2
4  Ferrari       5
5     Ford       6
6      BMW       1

In [21]:
df.describe() # numerical colums only

         counts
count  7.000000
mean   3.714286
std    2.288689
min    1.000000
25%    2.000000
50%    3.000000
75%    5.500000
max    7.000000

In [26]:
df.iloc[1:]

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       2
4  Ferrari       5
5     Ford       6
6      BMW       1

In [32]:
df.loc[:, "cars"]

0        BMW
1      Volvo
2       Ford
3      Tesla
4    Ferrari
5       Ford
6        BMW
Name: cars, dtype: object

In [37]:
df[df["counts"] >= 3] #filtring

      cars  counts
0      BMW       3
1    Volvo       7
4  Ferrari       5
5     Ford       6

In [38]:
df[df["cars"] == "BMW"] # filtring

  cars  counts
0  BMW       3
6  BMW       1

In [39]:
df.mean(numeric_only=True)

counts    3.714286
dtype: float64

In [40]:
df["counts"].mean()

np.float64(3.7142857142857144)

In [41]:
df.sum()

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                 26
dtype: object

In [42]:
df.min()

cars      BMW
counts      1
dtype: object

In [43]:
df.max()

cars      Volvo
counts        7
dtype: object

In [44]:
df.median(numeric_only=True)

counts    3.0
dtype: float64

In [45]:
df.count()

cars      7
counts    7
dtype: int64

In [46]:
df.std(numeric_only=True)

counts    2.288689
dtype: float64

In [47]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford"],
    "counts": [3, 7, None, 2, 5, 9, None,]
}

df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     2.0
4  Ferrari     5.0
5     None     9.0
6     Ford     NaN

In [49]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [54]:
df_missing.dropna(subset=["cars"])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     2.0
4  Ferrari     5.0
6     Ford     NaN

In [56]:
df_missing.fillna("unknown")

      cars   counts
0      BMW      3.0
1    Volvo      7.0
2  unknown  unknown
3    Tesla      2.0
4  Ferrari      5.0
5  unknown      9.0
6     Ford  unknown

In [60]:
df = pd.read_csv("Titanic-Dataset.csv")

df.head(10)

# df.pd.read_excel("Titanic-Dataset.xlsx")
# df.pd.read_json("Titanic-Dataset.json")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [61]:
df.to_excel("output.xlsx")

In [62]:
# Series => 1D
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [64]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']